runtime: python
service : client
env: flex

entrypoint : streamlit run 1_Home.py --server.port $PORT

runtime_config:
    python_version: 3

manual_scaling:
  instances: 1

env_variables:
  BASE_API_URL: "http://127:0:0:1:5000/"