runtime: python
service : default
env: flex

entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    python_version: 3

manual_scaling:
  instances: 1

env_variables:
  MONGODB_URI: "mongodb+srv://{0}:{1}@{2}/?retryWrites=true&w=majority"
  DB_USER: "luca"
  PASSW: "capstone"
  HOST: "charmender.1afwfzf.mongodb.net"
  DATABASE: "management"
  COLLECTIONS_LIST: "articles,transactions,customers"